name: Update Visitor Counter

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # 每小時執行一次

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Update Counter
        run: |
          COUNT_FILE="counter.json"
          if [ ! -f "$COUNT_FILE" ]; then
            echo '{"visits": 0}' > "$COUNT_FILE"
          fi
          VISITS=$(jq '.visits + 1' "$COUNT_FILE")
          echo "{\"visits\": $VISITS}" > "$COUNT_FILE"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add counter.json
          git commit -m "Update visitor counter"
          git push
