name: Visitor Counter
on:
  schedule:
    - cron: "*/20 * * * *"  # 每小時執行一次（可調整）
  workflow_dispatch:  # 允許手動觸發
  repository_dispatch:
    types: [visit]

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: 創建新的訪問 Issue
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository }}/issues \
               -d '{"title": "New Visitor", "labels": ["visitor-count"]}'
