name: Update Visitor Counter

on:
  repository_dispatch:
    types: [update-visitor-count]

jobs:
  update_counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Update Visitor Count
        run: |
          FILE="counter.json"
          if [ ! -f "$FILE" ]; then
            echo '{"count": 0}' > $FILE
          fi
          COUNT=$(jq '.count + 1' $FILE)
          echo "{\"count\": $COUNT}" > $FILE

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add counter.json
          git commit -m "Update visitor count" || echo "No changes to commit"
          git push
